name: hello_world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          chmod +x /home/runner/work/GitHubActDemo_01/GitHubActDemo_01/script.sh
          /home/runner/work/GitHubActDemo_01/GitHubActDemo_01/script.sh
